
(define (domain bakingrealistic)
  (:requirements :typing)
  (:types container butter_hypothetical measuring_cup oven dessert_hypothetical spatula egg_hypothetical powder_ingredient_hypothetical mixture_hypothetical electric_stand_mixer)
  
  (:predicates (sugar-is-consumed ?v0 - powder_ingredient_hypothetical)
	(baking-powder-is-consumed ?v0 - powder_ingredient_hypothetical)
	(tablespoons-of-flour-is-consumed ?v0 - powder_ingredient_hypothetical)
	(cups-of-flour-is-consumed ?v0 - powder_ingredient_hypothetical)
	(butter-is-consumed ?v0 - butter_hypothetical)
	(butter-in-container ?v0 - container ?v1 - butter_hypothetical)
	(butter-in-measuring-cup ?v0 - butter_hypothetical ?v1 - measuring_cup)
	(container-in-an-oven ?v0 - container)
	(container-in-oven ?v0 - container ?v1 - oven)
	(dessert-in-container ?v0 - container ?v1 - dessert_hypothetical)
	(dessert-is-hypothetical ?v0 - dessert_hypothetical)
	(different ?v0 - electric_stand_mixer ?v1 - electric_stand_mixer)
	(egg-in-container ?v0 - container ?v1 - egg_hypothetical)
	(egg-is-hypothetical ?v0 - egg_hypothetical)
	(is-baking-powder ?v0 - powder_ingredient_hypothetical)
	(is-bowl ?v0 - container)
	(is-butter ?v0 - butter_hypothetical)
	(is-cake ?v0 - dessert_hypothetical)
	(is-cups-of-flour ?v0 - powder_ingredient_hypothetical)
	(is-egg ?v0 - egg_hypothetical)
	(is-in-shell ?v0 - egg_hypothetical)
	(is-mixture ?v0 - mixture_hypothetical)
	(is-oven ?v0 - oven)
	(is-pan ?v0 - container)
	(is-plate ?v0 - container)
	(is-raw-egg-whites ?v0 - egg_hypothetical)
	(is-raw-egg-yolk ?v0 - egg_hypothetical)
	(is-souffle ?v0 - dessert_hypothetical)
	(is-sugar ?v0 - powder_ingredient_hypothetical)
	(is-tablespoons-of-flour ?v0 - powder_ingredient_hypothetical)
	(is-whipped-egg-whites ?v0 - egg_hypothetical)
	(is-whole-raw-egg ?v0 - egg_hypothetical)
	(mixture-has-baking-powder ?v0 - mixture_hypothetical)
	(mixture-has-butter ?v0 - mixture_hypothetical)
	(mixture-has-cups-of-flour ?v0 - mixture_hypothetical)
	(mixture-has-folded-raw-egg-whites ?v0 - mixture_hypothetical)
	(mixture-has-blended-raw-egg-whites ?v0 - mixture_hypothetical)
	(mixture-has-raw-egg-yolk ?v0 - mixture_hypothetical)
	(mixture-has-sugar ?v0 - mixture_hypothetical)
	(mixture-has-tablespoons-of-flour ?v0 - mixture_hypothetical)
	(mixture-in-container ?v0 - container ?v1 - mixture_hypothetical)
	(mixture-is-airy ?v0 - mixture_hypothetical)
	(mixture-is-hypothetical ?v0 - mixture_hypothetical)
	(name-less-than ?v0 - egg_hypothetical ?v1 - egg_hypothetical)
	(oven-is-full ?v0 - oven)
	(oven-is-heated-for-cake ?v0 - oven)
	(oven-is-heated-for-souffle ?v0 - oven)
	(pan-is-damaged ?v0 - container)
	(pan-is-full ?v0 - container)
	(powder-ingredient-in-container ?v0 - container ?v1 - powder_ingredient_hypothetical)
	(powder-ingredient-in-measuring-cup ?v0 - powder_ingredient_hypothetical ?v1 - measuring_cup)
	(beat-egg-whites ?v0 - electric_stand_mixer ?v1 - container ?v2 - egg_hypothetical)
	(crack-egg-and-put-in-container ?v0 - egg_hypothetical ?v1 - container)
	(fold-stiff-egg-whites-into-mixture ?v0 - spatula ?v1 - container ?v2 - container ?v3 - egg_hypothetical ?v4 - mixture_hypothetical)
	(move-baked-good-in-container-to-different-container ?v0 - container ?v1 - container ?v2 - dessert_hypothetical)
	(pour-mixture-only ?v0 - container ?v1 - container ?v2 - mixture_hypothetical)
	(pour-powdery-ingredient-from-container ?v0 - container ?v1 - container ?v2 - powder_ingredient_hypothetical)
	(pour-powdery-ingredient-from-measuring-cup ?v0 - powder_ingredient_hypothetical ?v1 - measuring_cup ?v2 - container)
	(preheat-oven-with-cake-settings ?v0 - oven)
	(preheat-oven-with-souffle-settings ?v0 - oven)
	(put-butter-in-container-from-measuring-cup ?v0 - butter_hypothetical ?v1 - container)
	(put-pan-in-oven ?v0 - container ?v1 - oven)
	(remove-pan-from-oven ?v0 - container ?v1 - oven)
	(separate-raw-yolk-from-egg-whites ?v0 - egg_hypothetical ?v1 - egg_hypothetical ?v2 - container ?v3 - container)
	(set-oven-with-cake-bake-time-and-press-start ?v0 - oven ?v1 - dessert_hypothetical ?v2 - mixture_hypothetical)
	(set-oven-with-souffle-bake-time-and-press-start ?v0 - oven ?v1 - dessert_hypothetical ?v2 - mixture_hypothetical)
	(transfer-butter-from-pan-or-bowl ?v0 - container ?v1 - container ?v2 - butter_hypothetical)
	(transfer-egg-from-pan-or-bowl ?v0 - container ?v1 - container ?v2 - egg_hypothetical)
	(use-stand-mixer ?v0 - electric_stand_mixer ?v1 - container ?v2 - mixture_hypothetical)
  )
  ; (:actions transfer-butter-from-pan-or-bowl beat-egg-whites set-oven-with-cake-bake-time-and-press-start preheat-oven-with-cake-settings set-oven-with-souffle-bake-time-and-press-start separate-raw-yolk-from-egg-whites transfer-egg-from-pan-or-bowl use-stand-mixer preheat-oven-with-souffle-settings pour-powdery-ingredient-from-measuring-cup crack-egg-and-put-in-container remove-pan-from-oven move-baked-good-in-container-to-different-container put-pan-in-oven pour-mixture-only pour-powdery-ingredient-from-container put-butter-in-container-from-measuring-cup fold-stiff-egg-whites-into-mixture)

  

	(:action bake-cake
		:parameters (?x0 - mixture_hypothetical ?x1 - dessert_hypothetical ?x2 - oven ?x3 - container)
		:precondition (and (set-oven-with-cake-bake-time-and-press-start ?x2 ?x1 ?x0)
			(oven-is-heated-for-cake ?x2)
			(dessert-is-hypothetical ?x1)
			(not (mixture-is-hypothetical ?x0))
			(container-in-oven ?x3 ?x2)
			(not (pan-is-full ?x3))
			(is-pan ?x3)
			(mixture-in-container ?x3 ?x0)
			(mixture-has-blended-raw-egg-whites ?x0)
			(mixture-has-raw-egg-yolk ?x0)
			(mixture-has-butter ?x0)
			(mixture-has-sugar ?x0)
			(mixture-has-cups-of-flour ?x0)
			(mixture-has-baking-powder ?x0)
			(not (mixture-is-airy ?x0)))
		:effect (and
			(not (is-mixture ?x0))
			(not (mixture-has-blended-raw-egg-whites ?x0))
			(not (mixture-has-raw-egg-yolk ?x0))
			(not (mixture-has-butter ?x0))
			(not (mixture-has-sugar ?x0))
			(not (mixture-has-cups-of-flour ?x0))
			(not (mixture-has-baking-powder ?x0))
			(not (mixture-in-container ?x3 ?x0))
			(not (dessert-is-hypothetical ?x1))
			(is-cake ?x1)
			(pan-is-full ?x3)
			(dessert-in-container ?x3 ?x1))
	)
	

	(:action bake-souffle
		:parameters (?x0 - mixture_hypothetical ?x1 - dessert_hypothetical ?x2 - oven ?x3 - container)
		:precondition (and (set-oven-with-souffle-bake-time-and-press-start ?x2 ?x1 ?x0)
			(oven-is-heated-for-souffle ?x2)
			(dessert-is-hypothetical ?x1)
			(is-mixture ?x0)
			(is-pan ?x3)
			(not (pan-is-full ?x3))
			(mixture-in-container ?x3 ?x0)
			(container-in-oven ?x3 ?x2)
			(not (mixture-is-hypothetical ?x0))
			(mixture-has-folded-raw-egg-whites ?x0)
			(mixture-has-raw-egg-yolk ?x0)
			(mixture-has-butter ?x0)
			(mixture-has-sugar ?x0)
			(not (mixture-has-cups-of-flour ?x0))
			(mixture-is-airy ?x0))
		:effect (and
			(not (is-mixture ?x0))
			(not (mixture-has-folded-raw-egg-whites ?x0))
			(not (mixture-has-raw-egg-yolk ?x0))
			(not (mixture-has-butter ?x0))
			(not (mixture-has-sugar ?x0))
			(not (mixture-has-tablespoons-of-flour ?x0))
			(not (mixture-is-airy ?x0))
			(not (mixture-in-container ?x3 ?x0))
			(not (dessert-is-hypothetical ?x1))
			(is-souffle ?x1)
			(pan-is-full ?x3)
			(dessert-in-container ?x3 ?x1))
	)
	

	(:action beat-egg-whites
		:parameters (?x0 - electric_stand_mixer ?x1 - container ?x2 - egg_hypothetical)
		:precondition (and (beat-egg-whites ?x0 ?x1 ?x2)
			(egg-in-container ?x1 ?x2)
			(is-raw-egg-whites ?x2)
			(is-egg ?x2)
			(not (egg-is-hypothetical ?x2)))
		:effect (and
			(is-whipped-egg-whites ?x2))
	)
	

	(:action crack-egg-in-container
		:parameters (?x0 - container ?x1 - egg_hypothetical)
		:precondition (and (crack-egg-and-put-in-container ?x1 ?x0)
			(not (egg-in-container ?x0 ?x1))
			(is-egg ?x1)
			(is-in-shell ?x1)
			(not (container-in-an-oven ?x0)))
		:effect (and
			(egg-in-container ?x0 ?x1)
			(is-whole-raw-egg ?x1)
			(not (is-in-shell ?x1)))
	)
	

	(:action fold-egg-whites-into-mixture
		:parameters (?x0 - spatula ?x1 - mixture_hypothetical ?x2 - container ?x3 - container ?x4 - egg_hypothetical)
		:precondition (and (fold-stiff-egg-whites-into-mixture ?x0 ?x3 ?x2 ?x4 ?x1)
			(mixture-in-container ?x2 ?x1)
			(egg-in-container ?x3 ?x4)
			(is-whipped-egg-whites ?x4)
			(not (egg-is-hypothetical ?x4))
			(is-mixture ?x1)
			(not (mixture-is-hypothetical ?x1))
			(not (container-in-an-oven ?x3))
			(not (container-in-an-oven ?x2))
			(different ?x3 ?x2))
		:effect (and
			(mixture-is-airy ?x1)
			(not (is-whipped-egg-whites ?x4))
			(not (is-egg ?x4))
			(mixture-has-folded-raw-egg-whites ?x1)
			(not (egg-in-container ?x3 ?x4)))
	)
	

	(:action place-dessert-on-plate
		:parameters (?x0 - dessert_hypothetical ?x1 - container ?x2 - container)
		:precondition (and (move-baked-good-in-container-to-different-container ?x2 ?x1 ?x0)
			(dessert-in-container ?x2 ?x0)
			(not (dessert-is-hypothetical ?x0))
			(is-plate ?x1)
			(not (container-in-an-oven ?x1))
			(not (container-in-an-oven ?x2))
			(different ?x2 ?x1))
		:effect (and
			(dessert-in-container ?x1 ?x0)
			(not (pan-is-full ?x2))
			(not (dessert-in-container ?x2 ?x0)))
	)
	

	(:action preheat-for-cake
		:parameters (?x0 - oven)
		:precondition (and (preheat-oven-with-cake-settings ?x0)
			(not (oven-is-heated-for-cake ?x0)))
		:effect (and
			(oven-is-heated-for-cake ?x0)
			(not (oven-is-heated-for-souffle ?x0)))
	)
	

	(:action preheat-for-souffle
		:parameters (?x0 - oven)
		:precondition (and (preheat-oven-with-souffle-settings ?x0)
			(not (oven-is-heated-for-souffle ?x0)))
		:effect (and
			(not (oven-is-heated-for-cake ?x0))
			(oven-is-heated-for-souffle ?x0))
	)
	

	(:action put-butter-in-bowl
		:parameters (?x0 - measuring_cup ?x1 - butter_hypothetical ?x2 - container)
		:precondition (and (put-butter-in-container-from-measuring-cup ?x1 ?x2)
			(is-butter ?x1)
			(not (butter-in-container ?x2 ?x1))
			(not (container-in-an-oven ?x2))
			(butter-in-measuring-cup ?x1 ?x0))
		:effect (and
			(butter-in-container ?x2 ?x1)
			(not (butter-in-measuring-cup ?x1 ?x0)))
	)
	

	(:action put-butter-in-pan
		:parameters (?x0 - measuring_cup ?x1 - butter_hypothetical ?x2 - container)
		:precondition (and (put-butter-in-container-from-measuring-cup ?x1 ?x2)
			(not (butter-in-container ?x2 ?x1))
			(is-butter ?x1)
			(is-pan ?x2)
			(not (container-in-an-oven ?x2))
			(butter-in-measuring-cup ?x1 ?x0))
		:effect (and
			(butter-in-container ?x2 ?x1)
			(not (butter-in-measuring-cup ?x1 ?x0)))
	)
	

	(:action put-pan-in-oven
		:parameters (?x0 - oven ?x1 - container)
		:precondition (and (put-pan-in-oven ?x1 ?x0)
			(is-pan ?x1)
			(not (container-in-an-oven ?x1))
			(not (oven-is-full ?x0)))
		:effect (and
			(container-in-oven ?x1 ?x0)
			(container-in-an-oven ?x1)
			(oven-is-full ?x0))
	)
	

	(:action put-powdery-ingredient-in-container
		:parameters (?x0 - measuring_cup ?x1 - container ?x2 - powder_ingredient_hypothetical)
		:precondition (and (pour-powdery-ingredient-from-measuring-cup ?x2 ?x0 ?x1)
			(not (powder-ingredient-in-container ?x1 ?x2))
			(not (container-in-an-oven ?x1))
			(powder-ingredient-in-measuring-cup ?x2 ?x0))
		:effect (and
			(powder-ingredient-in-container ?x1 ?x2)
			(not (powder-ingredient-in-measuring-cup ?x2 ?x0)))
	)
	

	(:action put-powdery-ingredient-into-container
		:parameters (?x0 - measuring_cup ?x1 - container ?x2 - powder_ingredient_hypothetical)
		:precondition (and (pour-powdery-ingredient-from-measuring-cup ?x2 ?x0 ?x1)
			(not (powder-ingredient-in-container ?x1 ?x2))
			(not (container-in-an-oven ?x1))
			(powder-ingredient-in-measuring-cup ?x2 ?x0))
		:effect (and
			(powder-ingredient-in-container ?x1 ?x2)
			(not (powder-ingredient-in-measuring-cup ?x2 ?x0)))
	)
	

	(:action remove-pan-from-oven
		:parameters (?x0 - oven ?x1 - container)
		:precondition (and (remove-pan-from-oven ?x1 ?x0)
			(container-in-oven ?x1 ?x0)
			(oven-is-full ?x0)
			(is-pan ?x1))
		:effect (and
			(not (oven-is-full ?x0))
			(not (container-in-oven ?x1 ?x0))
			(not (container-in-an-oven ?x1))
			(not (oven-is-heated-for-cake ?x0))
			(not (oven-is-heated-for-souffle ?x0)))
	)
	

	(:action separate-egg
		:parameters (?x0 - egg_hypothetical ?x1 - container ?x2 - container ?x3 - egg_hypothetical)
		:precondition (and (separate-raw-yolk-from-egg-whites ?x3 ?x0 ?x1 ?x2)
			(is-egg ?x3)
			(is-whole-raw-egg ?x3)
			(not (is-in-shell ?x3))
			(not (is-egg ?x0))
			(egg-is-hypothetical ?x0)
			(egg-in-container ?x1 ?x3)
			(different ?x2 ?x1)
			(different ?x3 ?x0))
		:effect (and
			(not (egg-is-hypothetical ?x0))
			(not (is-whole-raw-egg ?x3))
			(is-egg ?x0)
			(is-raw-egg-yolk ?x3)
			(is-raw-egg-whites ?x0)
			(egg-in-container ?x2 ?x0))
	)
	

	(:action transfer-butter
		:parameters (?x0 - butter_hypothetical ?x1 - container ?x2 - container)
		:precondition (and (transfer-butter-from-pan-or-bowl ?x2 ?x1 ?x0)
			(butter-in-container ?x2 ?x0)
			(is-butter ?x0)
			(not (container-in-an-oven ?x2))
			(not (container-in-an-oven ?x1))
			(different ?x2 ?x1))
		:effect (and
			(not (butter-in-container ?x2 ?x0))
			(butter-in-container ?x1 ?x0))
	)
	

	(:action transfer-egg
		:parameters (?x0 - egg_hypothetical ?x1 - container ?x2 - container)
		:precondition (and (transfer-egg-from-pan-or-bowl ?x2 ?x1 ?x0)
			(egg-in-container ?x2 ?x0)
			(not (egg-is-hypothetical ?x0))
			(is-egg ?x0)
			(not (container-in-an-oven ?x2))
			(not (container-in-an-oven ?x1))
			(different ?x2 ?x1))
		:effect (and
			(not (egg-in-container ?x2 ?x0))
			(egg-in-container ?x1 ?x0))
	)
	

	(:action transfer-mixture
		:parameters (?x0 - mixture_hypothetical ?x1 - container ?x2 - container)
		:precondition (and (pour-mixture-only ?x2 ?x1 ?x0)
			(mixture-in-container ?x2 ?x0)
			(not (mixture-is-hypothetical ?x0))
			(is-mixture ?x0)
			(not (container-in-an-oven ?x2))
			(not (container-in-an-oven ?x1))
			(not (pan-is-full ?x1))
			(different ?x2 ?x1))
		:effect (and
			(not (mixture-in-container ?x2 ?x0))
			(mixture-in-container ?x1 ?x0))
	)
	

	(:action transfer-powdery-ingredient
		:parameters (?x0 - powder_ingredient_hypothetical ?x1 - container ?x2 - container)
		:precondition (and (pour-powdery-ingredient-from-container ?x2 ?x1 ?x0)
			(powder-ingredient-in-container ?x2 ?x0)
			(not (container-in-an-oven ?x2))
			(not (container-in-an-oven ?x1))
			(different ?x2 ?x1))
		:effect (and
			(not (powder-ingredient-in-container ?x2 ?x0))
			(powder-ingredient-in-container ?x1 ?x0))
	)
	

	(:action use-stand-mixer-in-bowl-with-mixture-set1-baking-powder-butter-cups-of-flour-sugar-whole-raw-egg-butter-sugar-not-consumed
		:parameters (?x0 - mixture_hypothetical ?x1 - egg_hypothetical ?x10 - butter_hypothetical ?x11 - egg_hypothetical ?x12 - powder_ingredient_hypothetical ?x2 - container ?x3 - egg_hypothetical ?x4 - egg_hypothetical ?x5 - powder_ingredient_hypothetical ?x6 - powder_ingredient_hypothetical ?x7 - butter_hypothetical ?x8 - powder_ingredient_hypothetical ?x9 - electric_stand_mixer)
		:precondition (and (use-stand-mixer ?x9 ?x2 ?x0)
			(not (sugar-is-consumed ?x8))
			(not (butter-is-consumed ?x10))
			(not (baking-powder-is-consumed ?x6))
			(not (cups-of-flour-is-consumed ?x5))
			(is-bowl ?x2)
			(is-butter ?x7)
			(mixture-is-hypothetical ?x0)
			(butter-in-container ?x2 ?x10)
			(egg-in-container ?x2 ?x11)
			(is-baking-powder ?x6)
			(is-butter ?x10)
			(is-cups-of-flour ?x5)
			(is-sugar ?x8)
			(is-sugar ?x12)
			(is-whole-raw-egg ?x11)
			(powder-ingredient-in-container ?x2 ?x6)
			(powder-ingredient-in-container ?x2 ?x5)
			(powder-ingredient-in-container ?x2 ?x8)
			(not (egg-in-container ?x2 ?x4))
			(not (egg-in-container ?x2 ?x3))
			(not (egg-in-container ?x2 ?x1))
			(not (butter-in-container ?x2 ?x7))
			(not (powder-ingredient-in-container ?x2 ?x12))
			(different ?x6 ?x5)
			(different ?x6 ?x8)
			(different ?x5 ?x8)
			(different ?x4 ?x11)
			(different ?x4 ?x3)
			(name-less-than ?x4 ?x3)
			(different ?x4 ?x1)
			(name-less-than ?x4 ?x1)
			(different ?x11 ?x3)
			(different ?x11 ?x1)
			(different ?x3 ?x1)
			(name-less-than ?x3 ?x1)
			(different ?x6 ?x12)
			(different ?x7 ?x10)
			(different ?x5 ?x12)
			(different ?x12 ?x8))
		:effect (and
			(sugar-is-consumed ?x8)
			(butter-is-consumed ?x10)
			(cups-of-flour-is-consumed ?x5)
			(baking-powder-is-consumed ?x6)
			(mixture-in-container ?x2 ?x0)
			(is-mixture ?x0)
			(not (mixture-is-hypothetical ?x0))
			(mixture-has-baking-powder ?x0)
			(mixture-has-butter ?x0)
			(mixture-has-cups-of-flour ?x0)
			(mixture-has-sugar ?x0)
			(mixture-has-raw-egg-yolk ?x0)
			(mixture-has-blended-raw-egg-whites ?x0)
			(not (butter-in-container ?x2 ?x10))
			(not (egg-in-container ?x2 ?x11))
			(not (is-egg ?x11))
			(not (is-baking-powder ?x6))
			(not (is-butter ?x10))
			(not (is-cups-of-flour ?x5))
			(not (is-sugar ?x8))
			(not (is-whole-raw-egg ?x11))
			(not (powder-ingredient-in-container ?x2 ?x6))
			(not (powder-ingredient-in-container ?x2 ?x5))
			(not (powder-ingredient-in-container ?x2 ?x8)))
	)
	

	(:action use-stand-mixer-in-bowl-with-mixture-set1-baking-powder-butter-cups-of-flour-sugar-whole-raw-egg-butter-sugar-cupsflour-not-consumed
		:parameters (?x0 - mixture_hypothetical ?x1 - egg_hypothetical ?x10 - powder_ingredient_hypothetical ?x11 - butter_hypothetical ?x12 - powder_ingredient_hypothetical ?x13 - powder_ingredient_hypothetical ?x2 - electric_stand_mixer ?x3 - butter_hypothetical ?x4 - egg_hypothetical ?x5 - powder_ingredient_hypothetical ?x6 - container ?x7 - egg_hypothetical ?x8 - egg_hypothetical ?x9 - powder_ingredient_hypothetical)
		:precondition (and (use-stand-mixer ?x2 ?x6 ?x0)
			(not (sugar-is-consumed ?x12))
			(not (butter-is-consumed ?x3))
			(not (cups-of-flour-is-consumed ?x9))
			(not (baking-powder-is-consumed ?x10))
			(is-bowl ?x6)
			(is-butter ?x11)
			(mixture-is-hypothetical ?x0)
			(butter-in-container ?x6 ?x3)
			(egg-in-container ?x6 ?x4)
			(is-baking-powder ?x10)
			(is-butter ?x3)
			(is-cups-of-flour ?x9)
			(is-cups-of-flour ?x13)
			(is-sugar ?x12)
			(is-sugar ?x5)
			(is-whole-raw-egg ?x4)
			(powder-ingredient-in-container ?x6 ?x10)
			(powder-ingredient-in-container ?x6 ?x9)
			(not (powder-ingredient-in-container ?x6 ?x13))
			(powder-ingredient-in-container ?x6 ?x12)
			(not (egg-in-container ?x6 ?x8))
			(not (egg-in-container ?x6 ?x7))
			(not (egg-in-container ?x6 ?x1))
			(not (butter-in-container ?x6 ?x11))
			(not (powder-ingredient-in-container ?x6 ?x5))
			(different ?x10 ?x9)
			(different ?x10 ?x12)
			(different ?x9 ?x12)
			(different ?x8 ?x4)
			(different ?x8 ?x7)
			(name-less-than ?x8 ?x7)
			(different ?x8 ?x1)
			(name-less-than ?x8 ?x1)
			(different ?x4 ?x7)
			(different ?x4 ?x1)
			(different ?x7 ?x1)
			(name-less-than ?x7 ?x1)
			(different ?x10 ?x5)
			(different ?x11 ?x3)
			(different ?x9 ?x5)
			(different ?x5 ?x12))
		:effect (and
			(sugar-is-consumed ?x12)
			(butter-is-consumed ?x3)
			(cups-of-flour-is-consumed ?x9)
			(baking-powder-is-consumed ?x10)
			(mixture-in-container ?x6 ?x0)
			(is-mixture ?x0)
			(not (mixture-is-hypothetical ?x0))
			(mixture-has-baking-powder ?x0)
			(mixture-has-butter ?x0)
			(mixture-has-cups-of-flour ?x0)
			(mixture-has-sugar ?x0)
			(mixture-has-raw-egg-yolk ?x0)
			(mixture-has-blended-raw-egg-whites ?x0)
			(not (butter-in-container ?x6 ?x3))
			(not (egg-in-container ?x6 ?x4))
			(not (is-egg ?x4))
			(not (is-baking-powder ?x10))
			(not (is-butter ?x3))
			(not (is-cups-of-flour ?x9))
			(not (is-sugar ?x12))
			(not (is-whole-raw-egg ?x4))
			(not (powder-ingredient-in-container ?x6 ?x10))
			(not (powder-ingredient-in-container ?x6 ?x9))
			(not (powder-ingredient-in-container ?x6 ?x12)))
	)
	

	(:action use-stand-mixer-in-bowl-with-mixture-set1-baking-powder-butter-cups-of-flour-sugar-whole-raw-egg-butter-sugar-consumed
		:parameters (?x0 - mixture_hypothetical ?x1 - egg_hypothetical ?x10 - electric_stand_mixer ?x11 - butter_hypothetical ?x12 - egg_hypothetical ?x2 - powder_ingredient_hypothetical ?x3 - container ?x4 - egg_hypothetical ?x5 - egg_hypothetical ?x6 - powder_ingredient_hypothetical ?x7 - powder_ingredient_hypothetical ?x8 - butter_hypothetical ?x9 - powder_ingredient_hypothetical)
		:precondition (and (use-stand-mixer ?x10 ?x3 ?x0)
			(is-bowl ?x3)
			(butter-is-consumed ?x8)
			(not (sugar-is-consumed ?x9))
			(not (butter-is-consumed ?x11))
			(not (cups-of-flour-is-consumed ?x6))
			(not (baking-powder-is-consumed ?x7))
			(mixture-is-hypothetical ?x0)
			(butter-in-container ?x3 ?x11)
			(egg-in-container ?x3 ?x12)
			(is-baking-powder ?x7)
			(is-butter ?x11)
			(is-cups-of-flour ?x6)
			(is-sugar ?x9)
			(sugar-is-consumed ?x2)
			(is-whole-raw-egg ?x12)
			(powder-ingredient-in-container ?x3 ?x7)
			(powder-ingredient-in-container ?x3 ?x6)
			(powder-ingredient-in-container ?x3 ?x9)
			(not (egg-in-container ?x3 ?x5))
			(not (egg-in-container ?x3 ?x4))
			(not (egg-in-container ?x3 ?x1))
			(not (butter-in-container ?x3 ?x8))
			(not (powder-ingredient-in-container ?x3 ?x2))
			(different ?x7 ?x6)
			(different ?x7 ?x9)
			(different ?x6 ?x9)
			(different ?x5 ?x12)
			(different ?x5 ?x4)
			(name-less-than ?x5 ?x4)
			(different ?x5 ?x1)
			(name-less-than ?x5 ?x1)
			(different ?x12 ?x4)
			(different ?x12 ?x1)
			(different ?x4 ?x1)
			(name-less-than ?x4 ?x1)
			(different ?x7 ?x2)
			(different ?x8 ?x11)
			(different ?x6 ?x2)
			(different ?x2 ?x9))
		:effect (and
			(sugar-is-consumed ?x9)
			(butter-is-consumed ?x11)
			(cups-of-flour-is-consumed ?x6)
			(baking-powder-is-consumed ?x7)
			(mixture-in-container ?x3 ?x0)
			(is-mixture ?x0)
			(not (mixture-is-hypothetical ?x0))
			(mixture-has-baking-powder ?x0)
			(mixture-has-butter ?x0)
			(mixture-has-cups-of-flour ?x0)
			(mixture-has-sugar ?x0)
			(mixture-has-raw-egg-yolk ?x0)
			(mixture-has-blended-raw-egg-whites ?x0)
			(not (butter-in-container ?x3 ?x11))
			(not (egg-in-container ?x3 ?x12))
			(not (is-egg ?x12))
			(not (is-baking-powder ?x7))
			(not (is-butter ?x11))
			(not (is-cups-of-flour ?x6))
			(not (is-sugar ?x9))
			(not (is-whole-raw-egg ?x12))
			(not (powder-ingredient-in-container ?x3 ?x7))
			(not (powder-ingredient-in-container ?x3 ?x6))
			(not (powder-ingredient-in-container ?x3 ?x9)))
	)
	

	(:action use-stand-mixer-in-bowl-with-mixture-set1-baking-powder-butter-cups-of-flour-sugar-whole-raw-egg-butter-sugar-cupsflour-consumed
		:parameters (?x0 - mixture_hypothetical ?x1 - egg_hypothetical ?x10 - powder_ingredient_hypothetical ?x11 - butter_hypothetical ?x12 - powder_ingredient_hypothetical ?x13 - powder_ingredient_hypothetical ?x2 - electric_stand_mixer ?x3 - butter_hypothetical ?x4 - egg_hypothetical ?x5 - powder_ingredient_hypothetical ?x6 - container ?x7 - egg_hypothetical ?x8 - egg_hypothetical ?x9 - powder_ingredient_hypothetical)
		:precondition (and (use-stand-mixer ?x2 ?x6 ?x0)
			(is-bowl ?x6)
			(butter-is-consumed ?x11)
			(cups-of-flour-is-consumed ?x13)
			(mixture-is-hypothetical ?x0)
			(not (sugar-is-consumed ?x12))
			(not (butter-is-consumed ?x3))
			(not (cups-of-flour-is-consumed ?x9))
			(not (baking-powder-is-consumed ?x10))
			(butter-in-container ?x6 ?x3)
			(egg-in-container ?x6 ?x4)
			(is-baking-powder ?x10)
			(is-butter ?x3)
			(is-cups-of-flour ?x9)
			(is-sugar ?x12)
			(sugar-is-consumed ?x5)
			(is-whole-raw-egg ?x4)
			(powder-ingredient-in-container ?x6 ?x10)
			(powder-ingredient-in-container ?x6 ?x9)
			(powder-ingredient-in-container ?x6 ?x12)
			(not (egg-in-container ?x6 ?x8))
			(not (egg-in-container ?x6 ?x7))
			(not (egg-in-container ?x6 ?x1))
			(not (butter-in-container ?x6 ?x11))
			(not (powder-ingredient-in-container ?x6 ?x5))
			(different ?x10 ?x9)
			(different ?x10 ?x12)
			(different ?x9 ?x12)
			(different ?x8 ?x4)
			(different ?x8 ?x7)
			(name-less-than ?x8 ?x7)
			(different ?x8 ?x1)
			(name-less-than ?x8 ?x1)
			(different ?x4 ?x7)
			(different ?x4 ?x1)
			(different ?x7 ?x1)
			(name-less-than ?x7 ?x1)
			(different ?x10 ?x5)
			(different ?x11 ?x3)
			(different ?x9 ?x5)
			(different ?x5 ?x12))
		:effect (and
			(sugar-is-consumed ?x12)
			(butter-is-consumed ?x3)
			(cups-of-flour-is-consumed ?x9)
			(baking-powder-is-consumed ?x10)
			(not (mixture-is-airy ?x0))
			(mixture-in-container ?x6 ?x0)
			(is-mixture ?x0)
			(not (mixture-is-hypothetical ?x0))
			(mixture-has-baking-powder ?x0)
			(mixture-has-butter ?x0)
			(mixture-has-cups-of-flour ?x0)
			(mixture-has-sugar ?x0)
			(mixture-has-raw-egg-yolk ?x0)
			(mixture-has-blended-raw-egg-whites ?x0)
			(not (butter-in-container ?x6 ?x3))
			(not (egg-in-container ?x6 ?x4))
			(not (is-egg ?x4))
			(not (is-baking-powder ?x10))
			(not (is-butter ?x3))
			(not (is-cups-of-flour ?x9))
			(not (is-sugar ?x12))
			(not (is-whole-raw-egg ?x4))
			(not (powder-ingredient-in-container ?x6 ?x10))
			(not (powder-ingredient-in-container ?x6 ?x9))
			(not (powder-ingredient-in-container ?x6 ?x12)))
	)
	

	(:action use-stand-mixer-in-bowl-with-mixture-set1-butter-raw-egg-yolk-sugar-tablespoons-of-flour-butter-sugar-existing
		:parameters (?x0 - mixture_hypothetical ?x1 - egg_hypothetical ?x10 - butter_hypothetical ?x11 - egg_hypothetical ?x2 - powder_ingredient_hypothetical ?x3 - container ?x4 - egg_hypothetical ?x5 - egg_hypothetical ?x6 - powder_ingredient_hypothetical ?x7 - butter_hypothetical ?x8 - powder_ingredient_hypothetical ?x9 - electric_stand_mixer)
		:precondition (and (use-stand-mixer ?x9 ?x3 ?x0)
			(not (sugar-is-consumed ?x8))
			(not (butter-is-consumed ?x10))
			(not (tablespoons-of-flour-is-consumed ?x6))
			(is-butter ?x7)
			(not (powder-ingredient-in-container ?x3 ?x2))
			(is-bowl ?x3)
			(mixture-is-hypothetical ?x0)
			(butter-in-container ?x3 ?x10)
			(not (butter-in-container ?x3 ?x7))
			(egg-in-container ?x3 ?x11)
			(is-butter ?x10)
			(is-raw-egg-yolk ?x11)
			(is-sugar ?x8)
			(is-sugar ?x2)
			(is-tablespoons-of-flour ?x6)
			(powder-ingredient-in-container ?x3 ?x8)
			(powder-ingredient-in-container ?x3 ?x6)
			(not (egg-in-container ?x3 ?x5))
			(not (egg-in-container ?x3 ?x4))
			(not (egg-in-container ?x3 ?x1))
			(different ?x8 ?x2)
			(different ?x10 ?x7)
			(different ?x5 ?x11)
			(different ?x5 ?x4)
			(name-less-than ?x5 ?x4)
			(different ?x5 ?x1)
			(name-less-than ?x5 ?x1)
			(different ?x11 ?x4)
			(different ?x11 ?x1)
			(different ?x4 ?x1)
			(name-less-than ?x4 ?x1)
			(different ?x8 ?x6)
			(different ?x7 ?x10)
			(different ?x2 ?x8)
			(different ?x2 ?x6))
		:effect (and
			(sugar-is-consumed ?x8)
			(butter-is-consumed ?x10)
			(tablespoons-of-flour-is-consumed ?x6)
			(mixture-in-container ?x3 ?x0)
			(is-mixture ?x0)
			(not (mixture-is-hypothetical ?x0))
			(mixture-has-butter ?x0)
			(mixture-has-raw-egg-yolk ?x0)
			(mixture-has-sugar ?x0)
			(mixture-has-tablespoons-of-flour ?x0)
			(not (butter-in-container ?x3 ?x10))
			(not (egg-in-container ?x3 ?x11))
			(not (is-butter ?x10))
			(not (is-raw-egg-yolk ?x11))
			(not (is-egg ?x11))
			(not (is-sugar ?x8))
			(not (is-tablespoons-of-flour ?x6))
			(not (powder-ingredient-in-container ?x3 ?x8))
			(not (powder-ingredient-in-container ?x3 ?x6)))
	)
	

	(:action use-stand-mixer-in-bowl-with-mixture-set1-butter-raw-egg-yolk-sugar-tablespoons-of-flour-butter-sugar-consumed
		:parameters (?x0 - mixture_hypothetical ?x1 - egg_hypothetical ?x10 - powder_ingredient_hypothetical ?x11 - container ?x2 - egg_hypothetical ?x3 - egg_hypothetical ?x4 - powder_ingredient_hypothetical ?x5 - butter_hypothetical ?x6 - powder_ingredient_hypothetical ?x7 - electric_stand_mixer ?x8 - butter_hypothetical ?x9 - egg_hypothetical)
		:precondition (and (use-stand-mixer ?x7 ?x11 ?x0)
			(not (sugar-is-consumed ?x6))
			(not (butter-is-consumed ?x8))
			(not (tablespoons-of-flour-is-consumed ?x4))
			(sugar-is-consumed ?x10)
			(butter-is-consumed ?x5)
			(not (powder-ingredient-in-container ?x11 ?x10))
			(is-bowl ?x11)
			(mixture-is-hypothetical ?x0)
			(butter-in-container ?x11 ?x8)
			(not (butter-in-container ?x11 ?x5))
			(egg-in-container ?x11 ?x9)
			(is-butter ?x8)
			(is-raw-egg-yolk ?x9)
			(is-sugar ?x6)
			(is-tablespoons-of-flour ?x4)
			(powder-ingredient-in-container ?x11 ?x6)
			(powder-ingredient-in-container ?x11 ?x4)
			(not (egg-in-container ?x11 ?x3))
			(not (egg-in-container ?x11 ?x2))
			(not (egg-in-container ?x11 ?x1))
			(different ?x6 ?x10)
			(different ?x8 ?x5)
			(different ?x3 ?x9)
			(different ?x3 ?x2)
			(name-less-than ?x3 ?x2)
			(different ?x3 ?x1)
			(name-less-than ?x3 ?x1)
			(different ?x9 ?x2)
			(different ?x9 ?x1)
			(different ?x2 ?x1)
			(name-less-than ?x2 ?x1)
			(different ?x6 ?x4)
			(different ?x5 ?x8)
			(different ?x10 ?x6)
			(different ?x10 ?x4))
		:effect (and
			(sugar-is-consumed ?x6)
			(butter-is-consumed ?x8)
			(tablespoons-of-flour-is-consumed ?x4)
			(mixture-in-container ?x11 ?x0)
			(is-mixture ?x0)
			(not (mixture-is-hypothetical ?x0))
			(mixture-has-butter ?x0)
			(mixture-has-raw-egg-yolk ?x0)
			(mixture-has-sugar ?x0)
			(mixture-has-tablespoons-of-flour ?x0)
			(not (butter-in-container ?x11 ?x8))
			(not (egg-in-container ?x11 ?x9))
			(not (is-butter ?x8))
			(not (is-raw-egg-yolk ?x9))
			(not (is-egg ?x9))
			(not (is-sugar ?x6))
			(not (is-tablespoons-of-flour ?x4))
			(not (powder-ingredient-in-container ?x11 ?x6))
			(not (powder-ingredient-in-container ?x11 ?x4)))
	)
	

	(:action use-stand-mixer-in-bowl-with-mixture-set1-butter-raw-egg-yolk-sugar-tablespoons-of-flour-butter-sugar-tbflour-existing
		:parameters (?x0 - mixture_hypothetical ?x1 - egg_hypothetical ?x10 - butter_hypothetical ?x11 - powder_ingredient_hypothetical ?x12 - powder_ingredient_hypothetical ?x2 - electric_stand_mixer ?x3 - butter_hypothetical ?x4 - egg_hypothetical ?x5 - powder_ingredient_hypothetical ?x6 - container ?x7 - egg_hypothetical ?x8 - egg_hypothetical ?x9 - powder_ingredient_hypothetical)
		:precondition (and (use-stand-mixer ?x2 ?x6 ?x0)
			(not (sugar-is-consumed ?x11))
			(not (butter-is-consumed ?x3))
			(not (tablespoons-of-flour-is-consumed ?x9))
			(is-butter ?x10)
			(not (powder-ingredient-in-container ?x6 ?x5))
			(is-bowl ?x6)
			(mixture-is-hypothetical ?x0)
			(butter-in-container ?x6 ?x3)
			(not (butter-in-container ?x6 ?x10))
			(egg-in-container ?x6 ?x4)
			(is-butter ?x3)
			(is-raw-egg-yolk ?x4)
			(is-sugar ?x11)
			(is-sugar ?x5)
			(is-tablespoons-of-flour ?x9)
			(is-tablespoons-of-flour ?x12)
			(powder-ingredient-in-container ?x6 ?x11)
			(powder-ingredient-in-container ?x6 ?x9)
			(not (powder-ingredient-in-container ?x6 ?x12))
			(not (egg-in-container ?x6 ?x8))
			(not (egg-in-container ?x6 ?x7))
			(not (egg-in-container ?x6 ?x1))
			(different ?x11 ?x5)
			(different ?x3 ?x10)
			(different ?x8 ?x4)
			(different ?x8 ?x7)
			(name-less-than ?x8 ?x7)
			(different ?x8 ?x1)
			(name-less-than ?x8 ?x1)
			(different ?x4 ?x7)
			(different ?x4 ?x1)
			(different ?x7 ?x1)
			(name-less-than ?x7 ?x1)
			(different ?x11 ?x9)
			(different ?x10 ?x3)
			(different ?x5 ?x11)
			(different ?x5 ?x9))
		:effect (and
			(sugar-is-consumed ?x11)
			(butter-is-consumed ?x3)
			(tablespoons-of-flour-is-consumed ?x9)
			(mixture-in-container ?x6 ?x0)
			(is-mixture ?x0)
			(not (mixture-is-hypothetical ?x0))
			(mixture-has-butter ?x0)
			(mixture-has-raw-egg-yolk ?x0)
			(mixture-has-sugar ?x0)
			(mixture-has-tablespoons-of-flour ?x0)
			(not (butter-in-container ?x6 ?x3))
			(not (egg-in-container ?x6 ?x4))
			(not (is-butter ?x3))
			(not (is-raw-egg-yolk ?x4))
			(not (is-egg ?x4))
			(not (is-sugar ?x11))
			(not (is-tablespoons-of-flour ?x9))
			(not (powder-ingredient-in-container ?x6 ?x11))
			(not (powder-ingredient-in-container ?x6 ?x9)))
	)
	

	(:action use-stand-mixer-in-bowl-with-mixture-set1-butter-raw-egg-yolk-sugar-tablespoons-of-flour-butter-sugar-tbflour-consumed
		:parameters (?x0 - mixture_hypothetical ?x1 - egg_hypothetical ?x10 - butter_hypothetical ?x11 - powder_ingredient_hypothetical ?x12 - powder_ingredient_hypothetical ?x2 - electric_stand_mixer ?x3 - butter_hypothetical ?x4 - egg_hypothetical ?x5 - powder_ingredient_hypothetical ?x6 - container ?x7 - egg_hypothetical ?x8 - egg_hypothetical ?x9 - powder_ingredient_hypothetical)
		:precondition (and (use-stand-mixer ?x2 ?x6 ?x0)
			(not (sugar-is-consumed ?x11))
			(not (butter-is-consumed ?x3))
			(not (tablespoons-of-flour-is-consumed ?x9))
			(sugar-is-consumed ?x5)
			(butter-is-consumed ?x10)
			(tablespoons-of-flour-is-consumed ?x12)
			(not (powder-ingredient-in-container ?x6 ?x5))
			(is-bowl ?x6)
			(mixture-is-hypothetical ?x0)
			(butter-in-container ?x6 ?x3)
			(not (butter-in-container ?x6 ?x10))
			(egg-in-container ?x6 ?x4)
			(is-butter ?x3)
			(is-raw-egg-yolk ?x4)
			(is-sugar ?x11)
			(is-tablespoons-of-flour ?x9)
			(powder-ingredient-in-container ?x6 ?x11)
			(powder-ingredient-in-container ?x6 ?x9)
			(not (egg-in-container ?x6 ?x8))
			(not (egg-in-container ?x6 ?x7))
			(not (egg-in-container ?x6 ?x1))
			(different ?x11 ?x5)
			(different ?x3 ?x10)
			(different ?x8 ?x4)
			(different ?x8 ?x7)
			(name-less-than ?x8 ?x7)
			(different ?x8 ?x1)
			(name-less-than ?x8 ?x1)
			(different ?x4 ?x7)
			(different ?x4 ?x1)
			(different ?x7 ?x1)
			(name-less-than ?x7 ?x1)
			(different ?x11 ?x9)
			(different ?x10 ?x3)
			(different ?x5 ?x11)
			(different ?x5 ?x9))
		:effect (and
			(sugar-is-consumed ?x11)
			(butter-is-consumed ?x3)
			(tablespoons-of-flour-is-consumed ?x9)
			(mixture-in-container ?x6 ?x0)
			(is-mixture ?x0)
			(not (mixture-is-hypothetical ?x0))
			(mixture-has-butter ?x0)
			(mixture-has-raw-egg-yolk ?x0)
			(mixture-has-sugar ?x0)
			(mixture-has-tablespoons-of-flour ?x0)
			(not (butter-in-container ?x6 ?x3))
			(not (egg-in-container ?x6 ?x4))
			(not (is-butter ?x3))
			(not (is-raw-egg-yolk ?x4))
			(not (is-egg ?x4))
			(not (is-sugar ?x11))
			(not (is-tablespoons-of-flour ?x9))
			(not (powder-ingredient-in-container ?x6 ?x11))
			(not (powder-ingredient-in-container ?x6 ?x9)))
	)

  

)
        