(define (domain bakingrealistic)
    (:requirements :typing )
    (:types container measuring_cup dessert_hypothetical powder_ingredient_hypothetical butter_hypothetical mixture_hypothetical egg_hypothetical oven spatula electric_stand_mixer)
    (:predicates
        (powder-ingredient-in-measuring-cup ?p - powder_ingredient_hypothetical ?c - measuring_cup)
        (butter-in-measuring-cup ?b - butter_hypothetical ?c - measuring_cup)
        (dessert-is-hypothetical ?d - dessert_hypothetical)
        (mixture-is-hypothetical ?m - mixture_hypothetical)
        (egg-is-hypothetical ?e - egg_hypothetical)
        (is-baking-powder ?p - powder_ingredient_hypothetical)
        (is-raw-egg-yolk ?e - egg_hypothetical)
        (is-raw-egg-whites ?e - egg_hypothetical)
        (is-whipped-egg-whites ?e - egg_hypothetical)
        (is-in-shell ?e - egg_hypothetical)
        (is-whole-raw-egg ?e - egg_hypothetical)
        (is-egg ?e - egg_hypothetical)
        (mixture-is-airy ?m - mixture_hypothetical)
        (pan-is-damaged ?p - container)
        (is-whole-egg ?x - egg_hypothetical)
        (is-egg-yolk ?x - egg_hypothetical)
        (is-egg-white ?x - egg_hypothetical)
        (is-tablespoons-of-flour ?l - powder_ingredient_hypothetical)
        (is-cups-of-flour ?l - powder_ingredient_hypothetical)
        (is-sugar ?l - powder_ingredient_hypothetical)
        (is-butter ?b - butter_hypothetical)
        (oven-is-full ?o - oven)
        (is-pan ?c - container)
        (is-bowl ?c - container)
        (is-mixture ?m - mixture_hypothetical)
        (is-plate ?p - container)
        (container-is-full ?c - container)
        (powder-ingredient-in-container ?c - container ?x - powder_ingredient_hypothetical)
        (butter-in-container ?c - container ?x - butter_hypothetical)
        (egg-in-container ?c - container ?x - egg_hypothetical)
        (dessert-in-container ?c - container ?x - dessert_hypothetical)
        (mixture-in-container ?c - container ?x - mixture_hypothetical)
        (container-in-oven ?c - container ?o - oven)
        (container-in-an-oven ?c - container)
        (mixture-has-raw-egg-yolk ?x - mixture_hypothetical)
        (mixture-has-cups-of-flour ?x - mixture_hypothetical)
        (mixture-has-tablespoons-of-flour ?x - mixture_hypothetical)
        (mixture-has-raw-egg-whites ?x - mixture_hypothetical)
        (mixture-has-sugar ?x - mixture_hypothetical)
        (mixture-has-butter ?x - mixture_hypothetical)
        (mixture-has-baking-powder ?mixture - mixture_hypothetical)
        (is-cake ?new - dessert_hypothetical)
        (is-souffle ?new - dessert_hypothetical)
        (oven-is-heated-for-souffle ?o - oven)
        (oven-is-heated-for-cake ?o - oven)
        (pour-powdery-ingredient-from-measuring-cup ?p - powder_ingredient_hypothetical ?cup - measuring_cup ?c - container)
        (pour-mixture-only ?from - container ?into - container ?m - mixture_hypothetical)
        (pour-powdery-ingredient-from-container ?from - container ?into - container ?m - powder_ingredient_hypothetical)
        (transfer-butter-only ?from - container ?into - container ?m - butter_hypothetical)
        (transfer-egg-only ?from - container ?into - container ?m - egg_hypothetical)
        (move-baked-good-in-container-to-different-container ?from - container ?to - container)
        (crack-egg-and-put-in-container ?e - egg_hypothetical ?c - container)
        (put-butter-in-container ?b - butter_hypothetical ?c - container)
        (put-container-in-oven ?c - container ?o - oven)
        (preheat-oven-with-cake-settings ?o - oven)
        (preheat-oven-with-souffle-settings ?o - oven)
        (use-stand-mixer ?m - electric_stand_mixer ?c - container)
        (remove-pan-from-oven ?c - container)
        (start-baking-with-cake-settings ?o - oven)
        (start-baking-with-souffle-settings ?o - oven)
        (separate-raw-yolk-from-egg-whites ?e - egg_hypothetical ?new - egg_hypothetical)
        (beat ?m - electric_stand_mixer ?c - container ?e - egg_hypothetical)
        (fold ?s - spatula ?from - container ?to - container ?e - egg_hypothetical)


   )
    ; (:actions pour-powdery-ingredient-from-measuring-cup pour-mixture-only pour-powdery-ingredient-from-container transfer-butter-only transfer-egg-only move-baked-good-in-container-to-different-container crack-egg-and-put-in-container put-butter-in-container put-container-in-oven preheat-oven-with-cake-settings preheat-oven-with-souffle-settings use-stand-mixer remove-pan-from-oven start-baking-with-cake-settings start-baking-with-souffle-settings separate-raw-yolk-from-egg-whites beat fold)

(:action preheat-for-cake
:parameters (?o - oven)
:precondition (and 
    (preheat-oven-with-cake-settings ?o)
    (not (oven-is-heated-for-cake ?o))
)
:effect (and 
    (oven-is-heated-for-cake ?o)
    (not (oven-is-heated-for-souffle ?o))
)
; skill (preheat-oven-with-cake-settings ?o)
)

(:action preheat-for-souffle
:parameters (?o - oven)
:precondition (and
    (preheat-oven-with-souffle-settings ?o)
    (not (oven-is-heated-for-souffle ?o))
)
:effect (and
    (not (oven-is-heated-for-cake ?o))
    (oven-is-heated-for-souffle ?o)
)
; skill (preheat-oven-with-souffle-settings(?o - oven))
)



(:action separate-egg
:parameters (?x - egg_hypothetical ?y - egg_hypothetical ?c - container)
:precondition (and
    (separate-raw-yolk-from-egg-whites ?x ?y)
    (is-egg ?x)
    (is-whole-raw-egg ?x)
    (egg-in-container ?c ?x)
    (not (is-in-shell ?x))
    (not (is-egg ?y))
    (egg-is-hypothetical ?y)
)
:effect (and 
    (not (egg-is-hypothetical ?y))
    (not (is-whole-raw-egg ?x))
    (is-egg ?y)
    (is-raw-egg-yolk ?x)
    (is-raw-egg-whites ?y)
    (not (is-in-shell ?y))
    (egg-in-container ?c ?y)
)
; skill separate-raw-yolk-from-egg-whites(?x)
)

(:action put-butter-in-pan
:parameters (?b - butter_hypothetical ?p - container ?cup - measuring_cup)
:precondition (and 
    (put-butter-in-container ?b ?p)
    (is-butter ?b)
    (is-pan ?p)
    (not (butter-in-container ?p ?b))
    (not (container-in-an-oven ?p))
    (butter-in-measuring-cup ?b ?cup)
)
:effect (and
    (butter-in-container ?p ?b)
    (not (butter-in-measuring-cup ?b ?cup))
)
)

(:action put-powdery-ingredient-into-container
:parameters (?s - powder_ingredient_hypothetical ?p - container ?cup - measuring_cup)
:precondition (and
    (pour-powdery-ingredient-from-measuring-cup ?s ?cup ?p)
    (not (powder-ingredient-in-container ?p ?s))
    (not (container-in-an-oven ?p))
    (powder-ingredient-in-measuring-cup ?s ?cup)
)
:effect (and
    (powder-ingredient-in-container ?p ?s)
    (not (powder-ingredient-in-measuring-cup ?s ?cup))
))

(:action put-butter-in-bowl
:parameters (?butter - butter_hypothetical ?bowl - container ?cup - measuring_cup)
:precondition (and
    (put-butter-in-container ?butter ?bowl)
    (is-butter ?butter)
    (not (butter-in-container ?bowl ?butter))
    (not (container-in-an-oven ?bowl))
    (butter-in-measuring-cup ?butter ?cup)
)
:effect (and
    (butter-in-container ?bowl ?butter)
    (not (butter-in-measuring-cup ?butter ?cup))
)
)


(:action put-butter-in-pan
:parameters (?butter - butter_hypothetical ?pan - container ?cup - measuring_cup)
:precondition (and
    (put-butter-in-container ?butter ?pan)
    (not (butter-in-container ?pan ?butter))
    (is-butter ?butter)
    (is-pan ?pan)
    (not (container-in-an-oven ?pan))
    (butter-in-measuring-cup ?butter ?cup)
)
:effect (and
    (butter-in-container ?pan ?butter)
    (not (butter-in-measuring-cup ?butter ?cup))
)
)

(:action transfer-mixture
:parameters (?from - container ?to - container ?mixture - mixture_hypothetical)
:precondition (and
    (pour-mixture-only ?from ?to ?mixture)
    (mixture-in-container ?from ?mixture)
    (not (mixture-is-hypothetical ?mixture))
    (is-mixture ?mixture)
    (not (container-in-an-oven ?from))
    (not (container-in-an-oven ?to))
)
:effect (and
    (not (mixture-in-container ?from ?mixture))
    (mixture-in-container ?to ?mixture)
    (not (container-is-full ?from))
    (container-is-full ?to)
)
)

(:action transfer-egg
:parameters (?from - container ?to - container ?egg - egg_hypothetical)
:precondition (and
    (transfer-egg-only ?from ?to ?egg)
    (egg-in-container ?from ?egg)
    (not (egg-is-hypothetical ?egg))
    (is-egg ?egg)
    (not (container-in-an-oven ?from))
    (not (container-in-an-oven ?to))
)
:effect (and
    (not (egg-in-container ?from ?egg))
    (egg-in-container ?to ?egg)
    (not (container-is-full ?from))
)
)

(:action transfer-powdery-ingredient
:parameters (?from - container ?to - container ?p - powder_ingredient_hypothetical)
:precondition (and
    (pour-powdery-ingredient-from-container ?from ?to ?p)
    (powder-ingredient-in-container ?from ?p)
    (not (container-in-an-oven ?from))
    (not (container-in-an-oven ?to))
)
:effect (and
    (not (powder-ingredient-in-container ?from ?p))
    (powder-ingredient-in-container ?to ?p)
    (not (container-is-full ?from))
)
)


(:action transfer-butter
:parameters (?from - container ?to - container ?butter - butter_hypothetical)
:precondition (and
    (transfer-butter-only ?from ?to ?butter)
    (butter-in-container ?from ?butter)
    (is-butter ?butter)
    (not (container-in-an-oven ?from))
    (not (container-in-an-oven ?to))
)
:effect (and
    (not (butter-in-container ?from ?butter))
    (butter-in-container ?to ?butter)
    (not (container-is-full ?from))
)
)


(:action crack-egg-in-container
:parameters (?egg - egg_hypothetical ?c - container)
:precondition (and
    (crack-egg-and-put-in-container ?egg ?c)
    (not (egg-in-container ?c ?egg))
    (is-egg ?egg)
    (is-in-shell ?egg)
    (not (container-in-an-oven ?c))
)
:effect (and
    (egg-in-container ?c ?egg)
    (is-whole-raw-egg ?egg)
    (not (is-in-shell ?egg))
)
)

(:action put-powdery-ingredient-in-container
:parameters (?p - powder_ingredient_hypothetical ?c - container ?cup - measuring_cup)
:precondition (and
    (pour-powdery-ingredient-from-measuring-cup ?p ?cup ?c)
    (not (powder-ingredient-in-container ?c ?p))
    (not (container-in-an-oven ?c))
    (powder-ingredient-in-measuring-cup ?p ?cup)
)
:effect (and
    (powder-ingredient-in-container ?c ?p)
    (not (powder-ingredient-in-measuring-cup ?p ?cup))
)
)

(:action put-pan-in-oven
:parameters (?pan - container ?oven - oven)
:precondition (and
    (put-container-in-oven ?pan ?oven)
    (is-pan ?pan)
    (not (container-in-an-oven ?pan))
    (not (oven-is-full ?oven))
)
:effect (and
    (container-in-oven ?pan ?oven)
    (container-in-an-oven ?pan)
    (oven-is-full ?oven)
)
)

(:action remove-pan-from-oven
:parameters (?pan - container ?oven - oven)
:precondition (and 
    (remove-pan-from-oven ?pan)
    (container-in-oven ?pan ?oven)
    (is-pan ?pan)
)
:effect (and
    (not (oven-is-full ?oven))
    (not (container-in-oven ?pan ?oven))
    (not (container-in-an-oven ?pan))
    (not (oven-is-heated-for-cake ?oven))
    (not (oven-is-heated-for-souffle ?oven))
)
)

(:action bake-cake
:parameters (?oven - oven ?pan - container ?mixture - mixture_hypothetical ?cake - dessert_hypothetical)
:precondition (and
    (start-baking-with-cake-settings ?oven)
    (oven-is-heated-for-cake ?oven)
    (dessert-is-hypothetical ?cake)
    (not (mixture-is-hypothetical ?mixture))
    (container-in-oven ?pan ?oven)
    (is-pan ?pan)
   (mixture-in-container ?pan ?mixture)
   (mixture-has-raw-egg-whites ?mixture)
   (mixture-has-raw-egg-yolk ?mixture)
   (mixture-has-butter ?mixture)
    (mixture-has-sugar ?mixture)
    (mixture-has-cups-of-flour ?mixture)
    (mixture-has-baking-powder ?mixture)
   (not (mixture-is-airy ?mixture))
)
:effect (and
    (not (is-mixture ?mixture)) 
    (not (mixture-has-raw-egg-whites ?mixture))
    (not (mixture-has-raw-egg-yolk ?mixture))
    (not (mixture-has-butter ?mixture))
    (not (mixture-has-sugar ?mixture))
    (not (mixture-has-cups-of-flour ?mixture))
    (not (mixture-has-baking-powder ?mixture))
    (not (dessert-is-hypothetical ?cake))
    (is-cake ?cake)
    (dessert-in-container ?pan ?cake)
)
)

(:action bake-souffle
:parameters (?oven - oven ?pan - container ?mixture - mixture_hypothetical ?souffle - dessert_hypothetical)
:precondition (and
    (start-baking-with-souffle-settings ?oven)
    (oven-is-heated-for-souffle ?oven)
    (dessert-is-hypothetical ?souffle)
    (is-mixture ?mixture)
    (is-pan ?pan)
    (mixture-in-container ?pan ?mixture)
    (container-in-oven ?pan ?oven)
    (not (mixture-is-hypothetical ?mixture))
    (not (mixture-has-baking-powder ?mixture))
    (mixture-has-raw-egg-whites ?mixture)
    (mixture-has-raw-egg-yolk ?mixture)
    (mixture-has-butter ?mixture)
    (mixture-has-sugar ?mixture)
    (mixture-has-tablespoons-of-flour ?mixture)
  (mixture-is-airy ?mixture)
)
:effect (and
    (not (is-mixture ?mixture)) 
    (not (mixture-has-raw-egg-whites ?mixture))
    (not (mixture-has-raw-egg-yolk ?mixture))
    (not (mixture-has-butter ?mixture))
    (not (mixture-has-sugar ?mixture))
    (not (mixture-has-tablespoons-of-flour ?mixture))
    (not (mixture-is-airy ?mixture))
    (not (dessert-is-hypothetical ?souffle))
    (is-souffle ?souffle)
    (dessert-in-container ?pan ?souffle)
)
)


(:action beat-egg-whites
:parameters (?e - egg_hypothetical ?m - electric_stand_mixer ?c - container)
:precondition (and
    (beat ?m ?c ?e)
    (egg-in-container ?c ?e)
    (is-raw-egg-whites ?e)
    (is-egg ?e)
    (not (egg-is-hypothetical ?e))
)
:effect (and
    (is-whipped-egg-whites ?e)
)
)

(:action fold-egg-whites-into-mixture
:parameters (?e - egg_hypothetical ?m - mixture_hypothetical ?from - container ?to - container ?s - spatula)
:precondition (and
    (fold ?s ?from ?to ?e)
    (mixture-in-container ?to ?m)
    (egg-in-container ?from ?e)
    (is-whipped-egg-whites ?e)
    (not (egg-is-hypothetical ?e))
    (is-mixture ?m)
    (not (mixture-is-hypothetical ?m))
    (not (container-in-an-oven ?from))
    (not (container-in-an-oven ?to))
)
:effect (and
    (mixture-is-airy ?m)
    (not (is-whipped-egg-whites ?e))
    (not (is-egg ?e))
    (mixture-has-raw-egg-whites ?m)
    (not (egg-in-container ?from ?e))
    (egg-in-container ?to ?e)
)
)

(:action place-cake-on-plate
:parameters (?from - container ?to - container ?cake - dessert_hypothetical)
:precondition (and
    (move-baked-good-in-container-to-different-container ?from ?to)
    (dessert-in-container ?from ?cake)
    (not (dessert-is-hypothetical ?cake))
    (is-cake ?cake)
    (not (container-is-full ?to))
    (is-plate ?to)
    (not (container-in-an-oven ?to))
    (not (container-in-an-oven ?from))
)
:effect (and
    (container-is-full ?to)
    (dessert-in-container ?to ?cake)
    (not (dessert-in-container ?from ?cake))
    (not (container-is-full ?from))
)
)

(:action place-souffle-on-plate
:parameters (?from - container ?to - container ?souffle - dessert_hypothetical)
:precondition (and
    (move-baked-good-in-container-to-different-container ?from ?to)
    (dessert-in-container ?from ?souffle)
    (is-souffle ?souffle)
    (not (dessert-is-hypothetical ?souffle))
    (not (container-is-full ?to))
    (is-plate ?to)
    (not (container-in-an-oven ?to))
    (not (container-in-an-oven ?from))
)
:effect (and
    (container-is-full ?to)
    (dessert-in-container ?to ?souffle)
    (not (dessert-in-container ?from ?souffle))
    (not (container-is-full ?from))
)
)

(:action use-stand-mixer-in-bowl-with-butter-sugar-tablespoons-of-flour
:parameters (?mixer - electric_stand_mixer ?bowl - container ?mixture - mixture_hypothetical ?butter - butter_hypothetical ?sugar - powder_ingredient_hypothetical ?tablespoonsofflour - powder_ingredient_hypothetical)
:precondition (and
    (use-stand-mixer ?mixer ?bowl)
    (is-bowl ?bowl)
    (mixture-is-hypothetical ?mixture)
    (is-butter ?butter)
    (is-sugar ?sugar)
    (is-tablespoons-of-flour ?tablespoonsofflour)
    (butter-in-container ?bowl ?butter)
    (powder-ingredient-in-container ?bowl ?sugar)
    (powder-ingredient-in-container ?bowl ?tablespoonsofflour)
    (not     (container-is-full ?bowl))
)
:effect (and
    (is-mixture ?mixture)
    (not (mixture-is-hypothetical ?mixture))
    (mixture-in-container ?bowl ?mixture)
    (not (mixture-is-airy ?mixture))
    (not (is-butter ?butter))
    (not (is-sugar ?sugar))
    (not (is-tablespoons-of-flour ?tablespoonsofflour))
    (mixture-has-butter ?mixture)
    (mixture-has-sugar ?mixture)
    (mixture-has-tablespoons-of-flour ?mixture)
    (not (butter-in-container ?bowl ?butter))
    (not (powder-ingredient-in-container ?bowl ?sugar))
    (not (powder-ingredient-in-container ?bowl ?tablespoonsofflour))
    (container-is-full ?bowl)
)
)


(:action use-stand-mixer-in-bowl-with-wholeegg-baking-powder-butter-cups-of-flour-sugar
:parameters (?mixer - electric_stand_mixer ?bowl - container ?mixture - mixture_hypothetical ?wholerawegg - egg_hypothetical ?bakingpowder - powder_ingredient_hypothetical ?butter - butter_hypothetical ?cupsofflour - powder_ingredient_hypothetical ?sugar - powder_ingredient_hypothetical)
:precondition (and
    (use-stand-mixer ?mixer ?bowl)
    (is-bowl ?bowl)
    (mixture-is-hypothetical ?mixture)
    (is-whole-raw-egg ?wholerawegg)
    (is-baking-powder ?bakingpowder)
    (is-butter ?butter)
    (is-cups-of-flour ?cupsofflour)
    (is-sugar ?sugar)
    (egg-in-container ?bowl ?wholerawegg)
    (powder-ingredient-in-container ?bowl ?bakingpowder)
    (butter-in-container ?bowl ?butter)
    (powder-ingredient-in-container ?bowl ?cupsofflour)
    (powder-ingredient-in-container ?bowl ?sugar)
    (not (container-is-full ?bowl))
)
:effect (and
    (is-mixture ?mixture)
    (not (mixture-is-hypothetical ?mixture))
    (not (is-whole-raw-egg ?wholerawegg))
    (mixture-has-raw-egg-yolk ?mixture)
    (mixture-has-raw-egg-whites ?mixture)
    (mixture-in-container ?bowl ?mixture)
    (not (mixture-is-airy ?mixture))
    (not (is-baking-powder ?bakingpowder))
    (not (is-butter ?butter))
    (not (is-cups-of-flour ?cupsofflour))
    (not (is-sugar ?sugar))
    (not (egg-in-container ?bowl ?wholerawegg))
    (not (powder-ingredient-in-container ?bowl ?bakingpowder))
    (not (butter-in-container ?bowl ?butter))
    (not (powder-ingredient-in-container ?bowl ?cupsofflour))
    (not (powder-ingredient-in-container ?bowl ?sugar))
    (mixture-has-baking-powder ?mixture)
    (mixture-has-butter ?mixture)
    (mixture-has-cups-of-flour ?mixture)
    (mixture-has-sugar ?mixture)
    (container-is-full ?bowl)
)
)

(:action use-stand-mixer-in-bowl-with-wholeegg-baking-powder-butter-cups-of-flour-sugar
:parameters (?mixer - electric_stand_mixer ?bowl - container ?mixture - mixture_hypothetical ?wholerawegg - egg_hypothetical ?bakingpowder - powder_ingredient_hypothetical ?butter - butter_hypothetical ?cupsofflour - powder_ingredient_hypothetical ?sugar - powder_ingredient_hypothetical)
:precondition (and
    (use-stand-mixer ?mixer ?bowl)
    (is-bowl ?bowl)
    (mixture-is-hypothetical ?mixture)
    (is-whole-raw-egg ?wholerawegg)
    (egg-in-container ?bowl ?wholerawegg)
    (is-baking-powder ?bakingpowder)
    (is-butter ?butter)
    (is-cups-of-flour ?cupsofflour)
    (is-sugar ?sugar)
    (powder-ingredient-in-container ?bowl ?bakingpowder)
    (butter-in-container ?bowl ?butter)
    (powder-ingredient-in-container ?bowl ?cupsofflour)
    (powder-ingredient-in-container ?bowl ?sugar)
    (not (container-is-full ?bowl))
)
:effect (and
    (is-mixture ?mixture)
    (not (egg-in-container ?bowl ?wholerawegg))
    (not (mixture-is-hypothetical ?mixture))
    (not (is-whole-raw-egg ?wholerawegg))
    (mixture-has-raw-egg-yolk ?mixture)
    (mixture-has-raw-egg-whites ?mixture)
    (mixture-in-container ?bowl ?mixture)
    (not (mixture-is-airy ?mixture))
    (not (is-baking-powder ?bakingpowder))
    (not (is-butter ?butter))
    (not (is-cups-of-flour ?cupsofflour))
    (not (is-sugar ?sugar))
    (mixture-has-baking-powder ?mixture)
    (mixture-has-butter ?mixture)
    (mixture-has-cups-of-flour ?mixture)
    (mixture-has-sugar ?mixture)
    (not (powder-ingredient-in-container ?bowl ?bakingpowder))
    (not (butter-in-container ?bowl ?butter))
    (not (powder-ingredient-in-container ?bowl ?cupsofflour))
    (not (powder-ingredient-in-container ?bowl ?sugar))
    (container-is-full ?bowl)
)
)

(:action use-stand-mixer-in-bowl-with-wholeegg-butter-sugar-tablespoons-of-flour
:parameters (?mixer - electric_stand_mixer ?bowl - container ?mixture - mixture_hypothetical ?wholerawegg - egg_hypothetical ?butter - butter_hypothetical ?sugar - powder_ingredient_hypothetical ?tablespoonsofflour - powder_ingredient_hypothetical)
:precondition (and
    (use-stand-mixer ?mixer ?bowl)
    (is-bowl ?bowl)
    (mixture-is-hypothetical ?mixture)
    (is-whole-raw-egg ?wholerawegg)
    (egg-in-container ?bowl ?wholerawegg)
    (is-butter ?butter)
    (is-sugar ?sugar)
    (is-tablespoons-of-flour ?tablespoonsofflour)
    (butter-in-container ?bowl ?butter)
    (powder-ingredient-in-container ?bowl ?sugar)
    (powder-ingredient-in-container ?bowl ?tablespoonsofflour)
    (not     (container-is-full ?bowl))
)
:effect (and
    (is-mixture ?mixture)
    (not (egg-in-container ?bowl ?wholerawegg))
    (not (mixture-is-hypothetical ?mixture))
    (not (is-whole-raw-egg ?wholerawegg))
    (mixture-has-raw-egg-yolk ?mixture)
    (mixture-has-raw-egg-whites ?mixture)
    (mixture-in-container ?bowl ?mixture)
    (not (mixture-is-airy ?mixture))
    (not (is-butter ?butter))
    (not (is-sugar ?sugar))
    (not (is-tablespoons-of-flour ?tablespoonsofflour))
    (mixture-has-butter ?mixture)
    (mixture-has-sugar ?mixture)
    (mixture-has-tablespoons-of-flour ?mixture)
    (not (butter-in-container ?bowl ?butter))
    (not (powder-ingredient-in-container ?bowl ?sugar))
    (not (powder-ingredient-in-container ?bowl ?tablespoonsofflour))
    (container-is-full ?bowl)
)
)

(:action use-stand-mixer-in-bowl-with-butter-raw-egg-yolk-sugar-tablespoons-of-flour
:parameters (?mixer - electric_stand_mixer ?bowl - container ?mixture - mixture_hypothetical ?butter - butter_hypothetical ?raweggyolk - egg_hypothetical ?sugar - powder_ingredient_hypothetical ?tablespoonsofflour - powder_ingredient_hypothetical)
:precondition (and
    (use-stand-mixer ?mixer ?bowl)
    (is-bowl ?bowl)
    (mixture-is-hypothetical ?mixture)
    (is-butter ?butter)
    (is-raw-egg-yolk ?raweggyolk)
    (is-sugar ?sugar)
    (is-tablespoons-of-flour ?tablespoonsofflour)
    (butter-in-container ?bowl ?butter)
    (egg-in-container ?bowl ?raweggyolk)
    (powder-ingredient-in-container ?bowl ?sugar)
    (powder-ingredient-in-container ?bowl ?tablespoonsofflour)
    (not (container-is-full ?bowl))
)
:effect (and
    (is-mixture ?mixture)
    (not (mixture-is-hypothetical ?mixture))
    (mixture-in-container ?bowl ?mixture)
    (not (mixture-is-airy ?mixture))
    (not (is-butter ?butter))
    (not (is-raw-egg-yolk ?raweggyolk))
    (not (is-sugar ?sugar))
    (not (is-tablespoons-of-flour ?tablespoonsofflour))
    (mixture-has-butter ?mixture)
    (mixture-has-raw-egg-yolk ?mixture)
    (mixture-has-sugar ?mixture)
    (mixture-has-tablespoons-of-flour ?mixture)
    (not (butter-in-container ?bowl ?butter))
    (not (egg-in-container ?bowl ?raweggyolk))
    (not (powder-ingredient-in-container ?bowl ?sugar))
    (not (powder-ingredient-in-container ?bowl ?tablespoonsofflour))
    (container-is-full ?bowl)
)
)

(:action use-stand-mixer-in-pan-with-butter-sugar-tablespoons-of-flour
:parameters (?mixer - electric_stand_mixer ?pan - container ?mixture - mixture_hypothetical ?butter - butter_hypothetical ?sugar - powder_ingredient_hypothetical ?tablespoonsofflour - powder_ingredient_hypothetical)
:precondition (and
   (use-stand-mixer ?mixer ?pan)
   (is-pan ?pan)
   (mixture-is-hypothetical ?mixture)
   (is-butter ?butter)
   (is-sugar ?sugar)
   (is-tablespoons-of-flour ?tablespoonsofflour)
   (butter-in-container ?pan ?butter)
   (powder-ingredient-in-container ?pan ?sugar)
   (powder-ingredient-in-container ?pan ?tablespoonsofflour)
   (not (container-is-full ?pan))
)
:effect (and
   (pan-is-damaged ?pan)
   (is-mixture ?mixture)
   (not (mixture-is-hypothetical ?mixture))
   (mixture-in-container ?pan ?mixture)
   (not (mixture-is-airy ?mixture))
   (not (is-butter ?butter))
   (not (is-sugar ?sugar))
   (not (is-tablespoons-of-flour ?tablespoonsofflour))
   (mixture-has-butter ?mixture)
   (mixture-has-sugar ?mixture)
   (mixture-has-tablespoons-of-flour ?mixture)
   (container-is-full ?pan)
)
)


(:action use-stand-mixer-in-pan-with-butter-raw-egg-yolk-sugar-tablespoons-of-flour
:parameters (?mixer - electric_stand_mixer ?pan - container ?mixture - mixture_hypothetical ?butter - butter_hypothetical ?raweggyolk - egg_hypothetical ?sugar - powder_ingredient_hypothetical ?tablespoonsofflour - powder_ingredient_hypothetical)
:precondition (and
   (use-stand-mixer ?mixer ?pan)
   (is-pan ?pan)
   (mixture-is-hypothetical ?mixture)
   (is-butter ?butter)
   (is-raw-egg-yolk ?raweggyolk)
   (is-sugar ?sugar)
   (is-tablespoons-of-flour ?tablespoonsofflour)
   (butter-in-container ?pan ?butter)
   (egg-in-container ?pan ?raweggyolk)
   (powder-ingredient-in-container ?pan ?sugar)
   (powder-ingredient-in-container ?pan ?tablespoonsofflour)
   (not (container-is-full ?pan))
)
:effect (and
   (pan-is-damaged ?pan)
   (is-mixture ?mixture)
   (not (mixture-is-hypothetical ?mixture))
   (mixture-in-container ?pan ?mixture)
   (not (egg-in-container ?pan ?raweggyolk))
   (not (powder-ingredient-in-container ?pan ?sugar))
   (not (powder-ingredient-in-container ?pan ?tablespoonsofflour))
   (not (butter-in-container ?pan ?butter))
   (not (mixture-is-airy ?mixture))
   (not (is-butter ?butter))
   (not (is-raw-egg-yolk ?raweggyolk))
   (not (is-sugar ?sugar))
   (not (is-tablespoons-of-flour ?tablespoonsofflour))
   (mixture-has-butter ?mixture)
   (mixture-has-raw-egg-yolk ?mixture)
   (mixture-has-sugar ?mixture)
   (mixture-has-tablespoons-of-flour ?mixture)
   (container-is-full ?pan)
)
)

)


